"""Property-based and fuzz tests for the parser, the port, and the screener.

The example-based suites pin specific expected behaviour. These tests state the
*properties* that behaviour has to satisfy for inputs nobody thought to write down,
because that is where a safety tool actually breaks: an input no one enumerated.

Three properties carry most of the weight:

  1. TOTALITY. `SqlParser.parse` and `port_grammar` are total over their input
     domains. They raise exactly one documented exception type and nothing else --
     no `AttributeError` from a malformed tree, no `RecursionError` escaping, no
     `KeyError` from a missing token. This is the fail-closed property from
     model.py: if analysis cannot complete, the caller must be able to catch that
     and report UNKNOWN, so an undeclared exception type is a real defect, not a
     cosmetic one.
  2. INVARIANCE. The parse of a statement does not depend on how it was spelled.
     Case, surrounding whitespace, a trailing semicolon and a trailing comment must
     not change the statement label. This is the observable face of the
     `caseInsensitive` fix: the original port rejected `select 1` while real Spark
     accepted it, and the reason nobody noticed is that the example tests were all
     written in uppercase.
  3. NO FALSE ALLOW. `screen()` never returns ALLOW for source it could not
     analyze, and `Report.verdict` never ranks a DENY below an UNKNOWN. The whole
     value proposition is that a green report means "we looked"; a property test
     over generated PySpark is the cheapest way to keep that true as the policy
     layer grows.

Fuzz inputs are generated by Hypothesis, plus a seeded `random` sweep for the
`port_grammar` totality check where structured generation would be beside the
point -- the point is that *arbitrary* bytes either parse or raise `PortError`.

Known source bugs are recorded as non-strict xfails at the bottom, following the
convention in tests/test_folding.py. Nothing under src/ is modified here.
"""
from __future__ import annotations

import random
import re
import string

import pytest
from hypothesis import HealthCheck, assume, given, settings
from hypothesis import strategies as st

from sparkscreen.grammar.parser import SqlParser, SqlSyntaxError, get_parser
from sparkscreen.grammar.port import PortError, port_grammar
from sparkscreen.grammar.spec import SPECS, GrammarSpec
from sparkscreen.model import UNKNOWN_REASONS, Verdict
from sparkscreen.screen import screen

pytestmark = pytest.mark.fuzz

# Parsing is CPU-bound and the ANTLR runtime is not fast, so the default Hypothesis
# deadline (200ms) would flake on a loaded machine. Correctness here is about which
# exception type escapes, not how fast it arrives.
settings.register_profile(
    "sparkscreen",
    deadline=None,
    max_examples=40,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large],
)
settings.load_profile("sparkscreen")

KEYS = [s.key for s in SPECS]

# --------------------------------------------------------------------------- SQL corpus

#: Statements every pinned grammar accepts. Used as seeds for mutation and as the
#: base for invariance checks. Kept to constructs valid in both 3.5.1 and 4.0.
SEED_SQL = [
    "SELECT 1",
    "select a from t1 where a > 1 group by a having count(*) > 1 order by a limit 5",
    "with x as (select 1) select * from x",
    "drop table prod.users",
    "DROP TABLE IF EXISTS prod.users PURGE",
    "insert overwrite table prod.t select 1",
    "insert into t values (1)",
    "delete from t where id = 1",
    "alter table t add column b int",
    "create table t (a int) using parquet",
    "set spark.sql.shuffle.partitions=200",
    "show tables",
    "select cast(x as struct<a: int>) from t",
    "select a -> 'b' from t",
    "select /*+ BROADCAST(t) */ * from t",
    "select 'it''s quoted'",
    "explain select 1",
    "truncate table t",
]

_SQL_TEXT = st.sampled_from(SEED_SQL)

#: Fragments that stress the lexer: unterminated literals, bracketed comments,
#: dollar-quoting, unicode, embedded quotes, NUL-ish control characters.
_NOISE = st.sampled_from([
    "", " ", "\n", "\t", ";", " -- trailing", "\n/* c */", "/* unclosed",
    "'unterminated", '"', "$$", "`", "\x00", "é", "\U0001f600",
    "/*+ hint */", "$$x$$", "'a'||'b'", "/*", "*/", "\\",
])

#: Arbitrary text, for the totality property. Constrained to be short so the
#: RecursionError paths in the parser are reachable without a timeout.
_ARBITRARY_TEXT = st.text(max_size=60)

_PARSER_CACHE: dict[str, SqlParser] = {}


def _parser(key: str) -> SqlParser:
    if key not in _PARSER_CACHE:
        _PARSER_CACHE[key] = get_parser(key)
    return _PARSER_CACHE[key]


# ===========================================================================
# 1. TOTALITY
# ===========================================================================


@given(key=st.sampled_from(KEYS), text=_ARBITRARY_TEXT)
def test_parse_is_total_over_arbitrary_text(key, text):
    """PROPERTY: parse() returns a statement or raises SqlSyntaxError. Nothing else.

    Arbitrary bytes are the point: a garbage input must not be able to reach
    `AttributeError` inside the ANTLR runtime or the tree walker, because
    `screen()` catches only `SqlSyntaxError` at that call site. Any other escaping
    exception would turn "we couldn't analyze this" into an unhandled crash.
    """
    try:
        result = _parser(key).parse(text)
    except SqlSyntaxError:
        return
    except Exception as e:  # noqa: BLE001 - that is the assertion
        pytest.fail(f"{key}: {type(e).__name__} escaped parse(): {e!r}\ninput={text!r}")
    assert result.sql == text.strip()
    assert result.label


@given(key=st.sampled_from(KEYS), text=_ARBITRARY_TEXT)
def test_try_parse_never_raises(key, text):
    """PROPERTY: try_parse() is total -- it returns a statement or None, never raises.

    `try_parse` is documented as the "None means unparseable, which is NOT 'safe'"
    variant, so a caller can use it without a try/except. That contract only holds
    if no other exception type escapes.
    """
    result = _parser(key).try_parse(text)
    assert result is None or result.label


@given(key=st.sampled_from(KEYS), sql=_SQL_TEXT, noise=_NOISE)
def test_parse_is_total_with_trailing_noise(key, sql, noise):
    """PROPERTY: appending arbitrary noise never produces a non-SqlSyntaxError failure.

    Trailing junk is the shape of malformed input a real caller produces: a
    truncated statement, a stray comment, an unterminated string.
    """
    try:
        _parser(key).parse(sql + noise)
    except SqlSyntaxError:
        pass
    except Exception as e:  # noqa: BLE001
        pytest.fail(f"{key}: {type(e).__name__} escaped: {e!r}\ninput={(sql + noise)!r}")


@pytest.mark.parametrize("bad", [None, 1, 1.5, b"select 1", [], {}, object()])
def test_parse_rejects_non_string_input(bad):
    """PROPERTY: a non-str input raises SqlSyntaxError, not TypeError.

    `screen()` only ever passes str, but `parse` is a public API and its
    `SqlSyntaxError` contract should not have a hole for the wrong type.
    """
    with pytest.raises(SqlSyntaxError):
        SqlParser("spark-4.0").parse(bad)


@given(key=st.sampled_from(KEYS), text=st.text(alphabet=string.printable, max_size=50))
def test_parse_is_total_on_printable_grammar_text(key, text):
    """PROPERTY: pasting a grammar file into parse() fails closed, not loudly.

    Guards the case where SQL looks like a fragment of ANTLR syntax; the lexer
    should reject it as a syntax error rather than the runtime raising something
    unexpected while walking the resulting tree.
    """
    try:
        _parser(key).parse(text)
    except SqlSyntaxError:
        pass
    except Exception as e:  # noqa: BLE001
        pytest.fail(f"{key}: {type(e).__name__} escaped: {e!r}")


@given(text=_ARBITRARY_TEXT, is_lexer=st.booleans())
def test_port_grammar_only_raises_port_error(text, is_lexer):
    """PROPERTY: port_grammar raises PortError or returns a PortResult. Nothing else.

    `build.py` catches `PortError` to report "a human must extend port.py" and then
    catches bare `Exception` for everything else, so a `ValueError` from a malformed
    grammar is reported as a generic crash rather than as a port failure. This
    property holds for arbitrary text today; it is the guard that keeps it that
    way as `_strip_block` and the rewrite table grow.
    """
    try:
        port_grammar(text, is_lexer=is_lexer)
    except PortError:
        return
    except Exception as e:  # noqa: BLE001
        pytest.fail(f"{type(e).__name__} escaped port_grammar(): {e!r}\ninput={text!r}")


def test_port_grammar_tolerity_on_a_seeded_random_sweep():
    """Fuzz: 4000 random grammars, every one must raise PortError or succeed.

    Hypothesis's structured generation is the wrong tool here -- the claim is about
    *arbitrary* bytes, so this is a raw seeded sweep over a grammar-dense alphabet.
    Seeded so a failure is reproducible.
    """
    rng = random.Random(20240917)
    alphabet = string.printable + "SELECT'\"(){}[]<>:;?.@#$%^*&/|\\~`-"
    outcomes = {"ported": 0, "PortError": 0}
    for _ in range(4000):
        text = "".join(rng.choice(alphabet) for _ in range(rng.randint(0, 60)))
        is_lexer = rng.random() < 0.5
        try:
            port_grammar(text, is_lexer=is_lexer)
            outcomes["ported"] += 1
        except PortError:
            outcomes["PortError"] += 1
        except Exception as e:  # noqa: BLE001
            pytest.fail(f"{type(e).__name__} escaped: {e!r}\ninput={text!r}")
    assert outcomes["ported"] + outcomes["PortError"] == 4000


# ===========================================================================
# 2. INVARIANCE -- case, whitespace, semicolon, comment
# ===========================================================================

#: Every spelling variant here is accepted by real Spark, so the parser must agree.
#: `swapcase` is included because it is the sharpest form of the case bug: `SeLeCt`
#: matched neither an uppercase nor a lowercase keyword rule.
_SPELLINGS = {
    "lower": str.lower,
    "upper": str.upper,
    "swapcase": str.swapcase,
    "strip": str.strip,
    "pad": lambda s: f"   {s}  \n",
    "semicolon": lambda s: s + ";",
    "trailing_comment": lambda s: s + " -- x",
    "leading_comment": lambda s: "/* c */ " + s,
    "newline_pad": lambda s: "\n" + s + "\n\n",
}


@given(key=st.sampled_from(KEYS), sql=_SQL_TEXT,
       variant=st.sampled_from(sorted(_SPELLINGS)))
def test_label_is_invariant_under_reformatting(key, sql, variant):
    """PROPERTY: cosmetic reformatting never changes the top-level statement label.

    This is the observable form of the `caseInsensitive` fix, and it is the test
    that would have caught the original bug: every example-based test in
    tests/test_parser.py is written in a single case, so all of them passed while
    both grammars rejected all lowercase SQL that real Spark accepts.
    """
    base = _parser(key).parse(sql)
    reworded = _parser(key).parse(_SPELLINGS[variant](sql))
    assert reworded.label == base.label, (
        f"{key}: {variant} changed label {base.label} -> {reworded.label} for {sql!r}"
    )


@given(key=st.sampled_from(KEYS), sql=_SQL_TEXT)
def test_label_is_invariant_under_combined_reformatting(key, sql):
    """PROPERTY: the spellings compose -- case *and* whitespace *and* semicolon."""
    base = _parser(key).parse(sql)
    combined = f"  /* c */ {sql.lower()} ;  -- done\n"
    assert _parser(key).parse(combined).label == base.label


@given(key=st.sampled_from(KEYS), sql=_SQL_TEXT)
def test_parse_is_deterministic(key, sql):
    """PROPERTY: repeated parses of the same input give the same label and tree shape.

    The ANTLR runtime is not supposed to carry state between parses, but the lexer
    does hold mutable members (`complex_type_level_counter`, the dollar-quote tag
    deque) that the port introduced. A leak there would make a statement parse
    differently the second time, depending on what was parsed before it.
    """
    parser = _parser(key)
    labels = {parser.parse(sql).label for _ in range(4)}
    assert len(labels) == 1, f"{key}: parse is not deterministic: {labels}"


@given(key=st.sampled_from(KEYS), sql=_SQL_TEXT)
def test_lexer_state_does_not_leak_between_parses(key, sql):
    """PROPERTY: a parse does not change how the *next* parse behaves.

    Directly targets the mutable lexer members the port added
    (`complex_type_level_counter`, the dollar-quote tag deque, the
    `has_unclosed_bracketed_comment` flag). A leak there would make a statement
    parse differently the second time, depending on what was parsed before it --
    order-dependent screening results, which is close to undebuggable.

    The interleaved statements are chosen for what they do to that state, not for
    whether they parse on their own: `SELECT $$x$$` trips the dollar-quote tag push
    and pops, and `CAST(a AS STRUCT<b: INT>)` drives the type-level counter up and
    down. Note `$$x$$` is *rejected* by the parser (it is a codeLiteral, not a
    string), so it is driven for its lexer side effect and the rejection is fine.
    """
    parser = _parser(key)
    for interleave in (
        "SELECT 1",
        "SELECT $$x$$",
        "SELECT CAST(a AS STRUCT<b: INT>) FROM t",
        "/* unclosed",
    ):
        try:
            parser.parse(interleave)
        except SqlSyntaxError:
            pass
    assert parser.parse(sql).label == parser.parse(sql).label


@given(key=st.sampled_from(["spark-4.0"]), sql=_SQL_TEXT)
def test_script_flattening_yields_all_statements(key, sql):
    """PROPERTY: a BEGIN...END script yields one statement per inner statement.

    `_flatten` runs `effective_label` and `_tighten` over the tree, both of which
    re-point at inner subtrees. A bug there hands the policy layer a context whose
    label and subtree disagree -- the exact confusion `_tighten` exists to prevent.

    Scoped to spark-4.0: `BEGIN...END` scripts are a 4.0 addition, and 3.5.1
    correctly rejects them (there is no `compoundOrSingleStatement` rule to reach).

    Compares the *flattened* labels rather than `ParsedStatement.label`. A bare DML
    statement's top-level label is the wrapper `DmlStatement`, while `.statements`
    tightens it to the real kind (`InsertOverwriteTable`). That divergence is by
    design -- `_tighten` exists for it, and `screen()` reads `.statements`, not
    `.label` -- so the flattened form is the one with policy attached to it.

    SCRIPT_ONLY_LABELS covers the grammar's own asymmetry: a few statements have a
    distinct rule for the in-script form. `SET x=1` is `SetConfiguration` on its own
    and `SetVariableInsideSqlScript` inside BEGIN...END, because Spark distinguishes
    the two at the grammar level. See test_set_inside_a_script_is_unmatched_by_policy
    for the coverage consequence.
    """
    parser = _parser(key)
    single = [s.label for s in parser.parse(sql).statements]
    script = parser.parse(f"BEGIN {sql}; {sql}; END")
    labels = [s.label for s in script.statements]
    assert len(labels) == 2, f"expected 2 statements, got {labels}"
    assert all(labels), f"empty statement label in script: {labels}"
    expected = [SCRIPT_ONLY_LABELS.get(lbl, lbl) for lbl in single]
    assert labels == expected * 2, f"script {labels} != expected {expected * 2}"


#: Statements the grammar labels differently inside a BEGIN...END script.
SCRIPT_ONLY_LABELS = {
    "SetConfiguration": "SetVariableInsideSqlScript",
}


@pytest.mark.xfail(strict=False, reason=(
    "GAP (policy.py default rules): `SET k=v` inside BEGIN...END is labelled "
    "SetVariableInsideSqlScript, which no default rule matches, so review.config "
    "does not fire. Fail-closed -- the verdict is UNKNOWN either way -- but the "
    "rule that covers the bare form is silently skipped in the script form."
))
@given(sql=st.sampled_from([
    "set spark.sql.shuffle.partitions=200",
    "SET spark.sql.x=1",
    "set spark.sql.default.parallelism=8",
]))
def test_set_inside_a_script_is_matched_by_the_same_policy_rule(sql):
    """PROPERTY: a statement matches the same policy rule inside a script as outside.

    `review.config` lists `SetConfiguration`, but the in-script form of the same
    statement is labelled `SetVariableInsideSqlScript`, so the rule does not fire and
    the finding degrades from `review.config` to a bare
    `unsupported_statement`. Fail-closed, so not a security hole -- but a config
    statement a reviewer was meant to see disappears silently.

    Reproducer:
        from sparkscreen.screen import screen
        screen('import pyspark\\nspark.sql("set spark.sql.shuffle.partitions=200")\\n')
        #   -> unknown review.config review.config SetConfiguration
        screen('import pyspark\\nspark.sql("BEGIN set spark.sql.shuffle.partitions=200; END")\\n')
        #   -> unknown unsupported_statement None SetVariableInsideSqlScript
    """
    bare = screen(f'import pyspark\nspark.sql("{sql}")\n', spec="spark-4.0")
    wrapped = screen(f'import pyspark\nspark.sql("BEGIN {sql}; END")\n', spec="spark-4.0")
    bare_rules = {f.rule for f in bare.findings}
    wrapped_rules = {f.rule for f in wrapped.findings}
    assert bare_rules == wrapped_rules, (
        f"{sql!r}: bare matched {bare_rules}, script form matched {wrapped_rules}"
    )


@given(sql=_SQL_TEXT)
def test_begin_end_never_turns_a_deny_into_an_allow(sql):
    """PROPERTY: the BEGIN...END wrapper never turns a DENY into an ALLOW.

    The security-relevant direction of the flattening property, and the only one
    that matters: `screen()` evaluates `.statements`, so if `_flatten` mislabelled or
    dropped a statement, a DENY inside a script would silently become an ALLOW.

    Note this asserts *not more permissive*, not *identical*. A DENY that becomes
    UNKNOWN is still fail-closed -- it routes to a human rather than to production --
    so it is allowed here. Only ALLOW is forbidden, because that is the one verdict
    that tells the caller nobody looked.
    """
    bare = screen(f'import pyspark\nspark.sql("{sql}")\n', spec="spark-4.0")
    wrapped = screen(f'import pyspark\nspark.sql("BEGIN {sql}; END")\n', spec="spark-4.0")
    if bare.verdict is Verdict.DENY:
        assert wrapped.verdict is not Verdict.ALLOW, (
            f"BEGIN...END turned a DENY into an ALLOW for {sql!r}: {wrapped.summary()}"
        )


@given(key=st.sampled_from(KEYS), sql=_SQL_TEXT)
def test_wrapping_never_makes_a_verdict_more_permissive(key, sql):
    """PROPERTY: no version's BEGIN...END handling weakens a verdict.

    On 4.0 the wrapper is a real grammar construct and the verdict is preserved.
    On 3.5.1 the wrapper does not exist, so the whole script is unparseable and the
    verdict becomes UNKNOWN -- fail-closed, since UNKNOWN routes to a human.

    What must never happen in either direction is ALLOW appearing where a stricter
    verdict was.
    """
    bare = screen(f'import pyspark\nspark.sql("{sql}")\n', spec=key)
    wrapped = screen(f'import pyspark\nspark.sql("BEGIN {sql}; END")\n', spec=key)
    if bare.verdict is not Verdict.ALLOW:
        assert wrapped.verdict is not Verdict.ALLOW, (
            f"{key}: BEGIN...END relaxed {bare.verdict.value} to ALLOW for {sql!r}"
        )


@given(sql=_SQL_TEXT)
def test_begin_end_is_rejected_by_3_5_1(sql):
    """PROPERTY: 3.5.1 does not silently accept a construct it cannot represent.

    3.5.1 predates `BEGIN...END`, so wrapping must be a clean rejection that reaches
    the caller as UNKNOWN. Accepting it and flattening to the wrong statements would
    be a fail-open on a version whose grammar cannot express the construct.
    """
    assert _parser("spark-3.5.1").try_parse(f"BEGIN {sql}; END") is None
    report = screen(f'import pyspark\nspark.sql("BEGIN {sql}; END")\n', spec="spark-3.5.1")
    assert report.verdict is Verdict.UNKNOWN, (
        f"3.5.1 must report UNKNOWN for an unparseable script, got {report.summary()}"
    )


# ===========================================================================
# 3. NO FALSE ALLOW
# ===========================================================================

_PYSRC_SQL = st.sampled_from([
    'spark.sql("select 1")',
    'spark.sql("drop table prod.users")',
    'spark.sql("insert into t values (1)")',
    'spark.sql("select a from t where a > 1")',
    'spark.sql(f"select {x}")',
    'spark.sql("select " + x)',
    'df.createOrReplaceTempView("v")',
    'spark.sql("SET spark.sql.x=1")',
])


@given(src=st.text(max_size=200))
def test_screen_never_raises_on_arbitrary_text(src):
    """PROPERTY: screen() is total over arbitrary source text.

    It reports UNKNOWN for source it cannot analyze, so there must be no input that
    escapes as an unhandled exception. A crash here is a fail-open failure in the
    crudest sense: the caller gets no report at all.
    """
    try:
        report = screen(src)
    except Exception as e:  # noqa: BLE001
        pytest.fail(f"{type(e).__name__} escaped screen(): {e!r}\nsource={src!r}")
    assert report.verdict in tuple(Verdict)


@given(st.lists(_PYSRC_SQL, min_size=1, max_size=6))
def test_report_verdict_ranks_deny_above_unknown(statements):
    """PROPERTY: DENY > UNKNOWN > REVIEW > ALLOW, whatever the mix.

    Guards the aggregation bug model.py documents: deriving the verdict from the
    *reason* rather than the *verdict* made DELETE and MERGE -- which are
    `verdict=REVIEW, reason=DESTRUCTIVE_STATEMENT` -- report as ALLOW, so
    `DELETE FROM prod.users` was waved through.

    The order is total and the middle two are deliberately close: UNKNOWN outranks
    REVIEW because a file the screener could not read is the more urgent problem,
    but both refuse.
    """
    source = "import pyspark\n" + "\n".join(statements)
    report = screen(source)
    verdicts = {f.verdict for f in report.findings}
    if Verdict.DENY in verdicts:
        assert report.verdict is Verdict.DENY
    elif Verdict.UNKNOWN in verdicts:
        assert report.verdict is Verdict.UNKNOWN
    elif Verdict.REVIEW in verdicts:
        assert report.verdict is Verdict.REVIEW
    else:
        assert report.verdict is Verdict.ALLOW


@given(st.lists(_PYSRC_SQL, min_size=1, max_size=6))
def test_ok_is_equivalent_to_allow_with_no_findings(statements):
    """PROPERTY: `Report.ok` is True only for a clean ALLOW.

    The convenience predicate callers reach for must not be able to say "fine" while
    an analysis failure is sitting in the report.
    """
    report = screen("import pyspark\n" + "\n".join(statements))
    if report.ok:
        assert report.verdict is Verdict.ALLOW
        assert not report.analysis_failures
        assert all(f.verdict is Verdict.ALLOW for f in report.findings)


@given(st.lists(_PYSRC_SQL, min_size=1, max_size=6))
def test_unresolved_sinks_never_yield_allow(statements):
    """PROPERTY: an UNRESOLVED_DYNAMIC_SQL finding forces at least UNKNOWN.

    `spark.sql(f"select {x}")` cannot be folded, so it cannot be parsed, so it
    cannot be screened. The only safe verdict is UNKNOWN -- reporting ALLOW would
    be telling the user their dynamic SQL is fine when nobody ever looked at it.
    """
    assume(any("{" in s or "+" in s for s in statements))
    report = screen("import pyspark\nx = input()\n" + "\n".join(statements))
    assert report.verdict is not Verdict.ALLOW, (
        f"ALLOW with a dynamic sink: {report.summary()}"
    )


@given(st.lists(_PYSRC_SQL, min_size=1, max_size=6))
def test_analysis_failures_are_all_unknown_verdicts(statements):
    """PROPERTY: a finding whose reason means "we could not analyze" is UNKNOWN.

    `is_analysis_failure` and `is_unknown` are independent axes in the model, but
    the *first* one must never be true for a finding that claims to be a decision.
    """
    report = screen("import pyspark\n" + "\n".join(statements))
    for finding in report.analysis_failures:
        assert finding.reason in UNKNOWN_REASONS
        assert finding.is_unknown, (
            f"reason={finding.reason} is an analysis failure but verdict is "
            f"{finding.verdict}"
        )


@given(key=st.sampled_from(KEYS), sql=_SQL_TEXT)
def test_screening_is_deterministic(key, sql):
    """PROPERTY: screening the same source twice gives the same verdict.

    A policy decision that depends on call order or global state would be
    untestable in production and unauditable after the fact.
    """
    source = f'import pyspark\nspark.sql("{sql}")\n'
    first = screen(source, spec=key)
    second = screen(source, spec=key)
    assert first.verdict is second.verdict
    assert [f.to_dict() for f in first.findings] == [f.to_dict() for f in second.findings]


# ===========================================================================
# 4. STRUCTURAL PROPERTIES OF THE PINNED SPECS
# ===========================================================================


@given(key=st.sampled_from(KEYS))
def test_get_spec_round_trips_through_its_key(key):
    """PROPERTY: get_spec(get_spec(k).key) is the same spec object."""
    from sparkscreen.grammar.spec import get_spec

    assert get_spec(key).key == key
    assert get_spec(key) is get_spec(get_spec(key).key)


@given(version=st.sampled_from(sorted({v for s in SPECS for v in s.spark_versions})))
def test_spec_lookup_accepts_bare_and_v_prefixed_versions(version):
    """PROPERTY: `v3.5.1` and `3.5.1` resolve to the same pinned grammar.

    Spark version strings arrive with a `v` about half the time, from `spark-submit`
    output, from build files, and from humans typing into config.
    """
    from sparkscreen.grammar.spec import spec_for_spark_version

    assert spec_for_spark_version(version).key == spec_for_spark_version("v" + version).key
    assert spec_for_spark_version("  " + version + " ").key == spec_for_spark_version(version).key


@given(key=st.sampled_from(KEYS))
def test_every_pinned_grammar_actually_parses(key):
    """PROPERTY: each pinned Spark line has a working generated parser.

    Catches a committed-but-broken build, which would otherwise show up as
    "UNKNOWN for every statement" on exactly one Spark version.
    """
    parser = get_parser(key)
    assert parser.parse("select 1").label
    assert parser.parse("select a from t where a > 1").label
    with pytest.raises(SqlSyntaxError):
        parser.parse("SELCT 1")


# ===========================================================================
# Known source bugs
# ===========================================================================


@pytest.mark.xfail(strict=False, reason=(
    "BUG (port.py:154): fail-closed is an 11-string denylist (_JAVA_MARKERS), not an "
    "allowlist, so Java outside that list is copied verbatim into the generated "
    "Python. The module docstring claims 'An unrecognised one raises, so a Spark "
    "upgrade that adds new Java cannot silently produce a mis-parsing grammar', "
    "which is true only of the constructs that happen to be listed."
))
@given(action=st.sampled_from([
    '{x.add("a");}',                # collection mutation
    "{new java.util.ArrayList()}",  # fully-qualified allocation
    "{String s = getText();}",      # Java local declaration
    "{this.isHint()}",              # Java `this`
    "{if (true) { helper(); }}",    # Java control flow
    "{for (String s : xs) { f(s); }}",
]))
def test_no_java_survives_into_ported_grammar_propertywise(action):
    """PROPERTY: any Java placed in an inline action must raise, whatever it is.

    Reproducer (all of these return a PortResult instead of raising):
        src = ("/* s */\\nlexer grammar SqlBaseLexer;\\n@members {\\n"
               "  public boolean z() { return true; }\\n}\\n"
               f"A : 'a' {{{action}}} ;\\n")
        port_grammar(src, is_lexer=True).text   # -> contains the Java verbatim
    """
    src = ("/* s */\nlexer grammar SqlBaseLexer;\n@members {\n"
           "  public boolean z() { return true; }\n}\n"
           f"A : 'a' {{{action}}} ;\n")
    with pytest.raises(PortError):
        port_grammar(src, is_lexer=True)


def test_port_grammar_missing_license_is_a_port_error():
    """PROPERTY: every rejection from port_grammar is a PortError.

    Reproducer:
        port_grammar("lexer grammar L;\\n@members {\\n  public boolean z() "
                     "{ return true; }\\n}\\nA:'a';\\n", is_lexer=True)
        # -> ValueError: substring not found
    """
    with pytest.raises(PortError):
        port_grammar(
            "lexer grammar SqlBaseLexer;\n@members {\n"
            "  public boolean z() { return true; }\n}\nA : 'a' ;\n",
            is_lexer=True,
        )


@pytest.mark.xfail(strict=False, reason=(
    "BUG (port.py:116): the docstring claims port_grammar 'asserts that no rewrite is "
    "left unused', but unused_rules is only recorded and port_to_python discards it. "
    "spark-3.5.1 has 6 unused lexer rewrites and 6 unused parser rewrites today."
))
def test_unused_rewrites_are_surfaced_propertywise():
    """PROPERTY: a rewrite that no longer matches any pinned grammar is reported.

    A Spark upgrade that drops a construct should not leave dead rewrites behind
    silently; the docstring says they are reported.
    """
    total = 0
    for spec in SPECS:
        for name in spec.files:
            result = port_grammar(
                spec.vendored_path(name).read_text(),
                is_lexer=name.endswith("Lexer"),
            )
            total += len(result.unused_rules)
    assert total == 0, f"{total} rewrites no longer match any pinned grammar"
